name: minimal_impl
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: 1.0.0+5
  provider: 4.1.2

flutter:
  uses-material-design: true
